#!/usr/bin/env bash
# setup.sh — Interactive first-time configuration wizard.
# Run once before the first `make deploy`.
set -euo pipefail

# ── Colours ─────────────────────────────────────────────────────────────────
GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

ok()   { echo -e "  ${GREEN}✓${RESET} $*"; }
ask()  { echo -e "  ${YELLOW}?${RESET} $*"; }
err()  { echo -e "  ${RED}✗${RESET} $*" >&2; }
info() { echo -e "  ${CYAN}ℹ${RESET} $*"; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEPLOY_DIR="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$DEPLOY_DIR/.env"

echo ""
echo -e "${BOLD}════════════════════════════════════════════════${RESET}"
echo -e "${BOLD}   Minecraft AI Manager — Setup Wizard          ${RESET}"
echo -e "${BOLD}════════════════════════════════════════════════${RESET}"
echo ""

# ── Prerequisite checks ──────────────────────────────────────────────────────
echo -e "${BOLD}Checking prerequisites...${RESET}"

if ! command -v docker &>/dev/null; then
  err "Docker not found. Install it from https://docs.docker.com/engine/install/"
  exit 1
fi
ok "Docker $(docker --version 2>/dev/null | awk '{print $3}' | tr -d ',' || echo 'installed')"

if ! docker compose version &>/dev/null; then
  err "Docker Compose plugin not found. Run: sudo apt install docker-compose-plugin"
  exit 1
fi
ok "Docker Compose $(docker compose version 2>/dev/null | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1 || echo 'installed')"

if [[ -f "$ENV_FILE" ]]; then
  ask ".env already exists. Overwrite? [y/N]"
  read -r answer
  if [[ ! "$answer" =~ ^[Yy]$ ]]; then
    info "Keeping existing .env. Skipping setup."
    exit 0
  fi
fi

echo ""
echo -e "${BOLD}Let's configure your deployment:${RESET}"
echo -e "  ${CYAN}(Press Enter to accept the default shown in brackets)${RESET}"
echo ""

# ── Collect user inputs ──────────────────────────────────────────────────────
ask "Web panel port [80]:"
read -r HTTP_PORT
HTTP_PORT="${HTTP_PORT:-80}"

echo ""
echo -e "${BOLD}Admin account (web panel login):${RESET}"
ask "Admin email:"
read -r ADMIN_EMAIL
while [[ -z "$ADMIN_EMAIL" ]]; do
  err "Admin email cannot be empty."
  ask "Admin email:"
  read -r ADMIN_EMAIL
done

ask "Admin password (min 12 chars):"
read -rs ADMIN_PASSWORD || true
echo ""
while [[ ${#ADMIN_PASSWORD} -lt 12 ]]; do
  err "Password must be at least 12 characters."
  ask "Admin password:"
  read -rs ADMIN_PASSWORD || true
  echo ""
done

echo ""
echo -e "${BOLD}Minecraft RCON (server console access):${RESET}"
ask "RCON port [25575]:"
read -r RCON_PORT
RCON_PORT="${RCON_PORT:-25575}"

ask "RCON password (auto-generate? press Enter):"
read -rs RCON_PASSWORD_INPUT || true
echo ""

echo ""
echo -e "${BOLD}MCP server (Claude AI tool access):${RESET}"
ask "MCP port [3100]:"
read -r MCP_PORT
MCP_PORT="${MCP_PORT:-3100}"

ask "MCP auth token (auto-generate? press Enter):"
read -rs MCP_AUTH_TOKEN_INPUT || true
echo ""

echo ""
echo -e "${BOLD}Generating secrets...${RESET}"

gen_secret() { openssl rand -hex "$1" 2>/dev/null || head -c "$1" /dev/urandom | xxd -p | tr -d '\n' | head -c $(( $1 * 2 )); }

POSTGRES_PASSWORD=$(gen_secret 20)
REDIS_PASSWORD=$(gen_secret 20)
JWT_SECRET=$(gen_secret 32)
JWT_REFRESH_SECRET=$(gen_secret 32)
BRIDGE_SECRET=$(gen_secret 16)
RCON_PASSWORD="${RCON_PASSWORD_INPUT:-$(gen_secret 16)}"
MCP_AUTH_TOKEN="${MCP_AUTH_TOKEN_INPUT:-$(gen_secret 20)}"

ok "POSTGRES_PASSWORD"
ok "REDIS_PASSWORD"
ok "JWT_SECRET"
ok "JWT_REFRESH_SECRET"
ok "BRIDGE_SECRET"
ok "RCON_PASSWORD"
ok "MCP_AUTH_TOKEN"

# ── Write .env ───────────────────────────────────────────────────────────────
cat > "$ENV_FILE" <<EOF
# Generated by setup.sh on $(date -u +"%Y-%m-%d %H:%M UTC")
# Do NOT commit this file to git.

# ── Server ──────────────────────────────────────────────────────────────────
HTTP_PORT=${HTTP_PORT}

# ── Database ────────────────────────────────────────────────────────────────
POSTGRES_DB=craftcontrol
POSTGRES_USER=craftcontrol
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

# ── Redis ───────────────────────────────────────────────────────────────────
REDIS_PASSWORD=${REDIS_PASSWORD}

# ── JWT ─────────────────────────────────────────────────────────────────────
JWT_SECRET=${JWT_SECRET}
JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
JWT_EXPIRES_IN=15m
JWT_REFRESH_EXPIRES_IN=7d

# ── Plugin bridge ────────────────────────────────────────────────────────────
BRIDGE_SECRET=${BRIDGE_SECRET}

# ── Minecraft server ────────────────────────────────────────────────────────
MINECRAFT_VERSION=1.21.1
MINECRAFT_MEMORY=4G

# ── Minecraft RCON ──────────────────────────────────────────────────────────
RCON_PORT=${RCON_PORT}
RCON_PASSWORD=${RCON_PASSWORD}

# ── Admin account ────────────────────────────────────────────────────────────
ADMIN_EMAIL=${ADMIN_EMAIL}
ADMIN_PASSWORD=${ADMIN_PASSWORD}

# ── MCP server (Claude AI tool access) ──────────────────────────────────────
MCP_PORT=${MCP_PORT}
MCP_AUTH_TOKEN=${MCP_AUTH_TOKEN}

# ── Docker image tag (set automatically by deploy.sh) ────────────────────────
IMAGE_TAG=latest
EOF

chmod 600 "$ENV_FILE"

# ── Summary ──────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}${BOLD}✓ .env created successfully!${RESET}"
echo ""
echo -e "${BOLD}════ MCP server (Claude AI tools) ═══════════════${RESET}"
echo -e "Add to Claude Desktop / Claude Code config:"
echo ""
echo -e "  ${CYAN}{${RESET}"
echo -e "  ${CYAN}  \"mcpServers\": {${RESET}"
echo -e "  ${CYAN}    \"craftcontrol\": {${RESET}"
echo -e "  ${CYAN}      \"transport\": \"sse\",${RESET}"
echo -e "  ${CYAN}      \"url\": \"http://$(hostname -I | awk '{print $1}'):${MCP_PORT}/sse\",${RESET}"
echo -e "  ${CYAN}      \"headers\": { \"Authorization\": \"Bearer ${MCP_AUTH_TOKEN}\" }${RESET}"
echo -e "  ${CYAN}    }${RESET}"
echo -e "  ${CYAN}  }${RESET}"
echo -e "  ${CYAN}}${RESET}"
echo ""
echo -e "${BOLD}════ Next step ══════════════════════════════════${RESET}"
echo -e "  Run: ${BOLD}make deploy${RESET}"
echo ""
