#!/usr/bin/env bash
# setup.sh — Interactive first-time configuration wizard.
# Run once before the first `make deploy`.
set -euo pipefail

# ── Colours ─────────────────────────────────────────────────────────────────
GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

ok()   { echo -e "  ${GREEN}✓${RESET} $*"; }
ask()  { echo -e "  ${YELLOW}?${RESET} $*"; }
err()  { echo -e "  ${RED}✗${RESET} $*" >&2; }
info() { echo -e "  ${CYAN}ℹ${RESET} $*"; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEPLOY_DIR="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$DEPLOY_DIR/.env"

echo ""
echo -e "${BOLD}════════════════════════════════════════════════${RESET}"
echo -e "${BOLD}   Minecraft AI Manager — Setup Wizard          ${RESET}"
echo -e "${BOLD}════════════════════════════════════════════════${RESET}"
echo ""

# ── Prerequisite checks ──────────────────────────────────────────────────────
echo -e "${BOLD}Checking prerequisites...${RESET}"

if ! command -v docker &>/dev/null; then
  err "Docker not found. Install it from https://docs.docker.com/engine/install/"
  exit 1
fi
ok "Docker $(docker --version | awk '{print $3}' | tr -d ',')"

if ! docker compose version &>/dev/null; then
  err "Docker Compose plugin not found. Run: sudo apt install docker-compose-plugin"
  exit 1
fi
ok "Docker Compose $(docker compose version --short)"

if [[ -f "$ENV_FILE" ]]; then
  ask ".env already exists. Overwrite? [y/N]"
  read -r answer
  if [[ ! "$answer" =~ ^[Yy]$ ]]; then
    info "Keeping existing .env. Skipping setup."
    exit 0
  fi
fi

echo ""
echo -e "${BOLD}Let's configure your deployment:${RESET}"
echo -e "  ${CYAN}(Press Enter to accept the default shown in brackets)${RESET}"
echo ""

# ── Collect user inputs ──────────────────────────────────────────────────────
ask "Game server IP or hostname [10.10.10.10]:"
read -r GAME_VM_HOST
GAME_VM_HOST="${GAME_VM_HOST:-10.10.10.10}"

ask "Web panel port [80]:"
read -r HTTP_PORT
HTTP_PORT="${HTTP_PORT:-80}"

echo ""
echo -e "${BOLD}Generating secrets...${RESET}"

gen_secret() { openssl rand -hex "$1" 2>/dev/null || head -c "$1" /dev/urandom | xxd -p | tr -d '\n' | head -c $(( $1 * 2 )); }

POSTGRES_PASSWORD=$(gen_secret 20)
REDIS_PASSWORD=$(gen_secret 20)
JWT_SECRET=$(gen_secret 32)
JWT_REFRESH_SECRET=$(gen_secret 32)
BRIDGE_SECRET=$(gen_secret 16)

ok "POSTGRES_PASSWORD"
ok "REDIS_PASSWORD"
ok "JWT_SECRET"
ok "JWT_REFRESH_SECRET"
ok "BRIDGE_SECRET"

# ── Write .env ───────────────────────────────────────────────────────────────
cat > "$ENV_FILE" <<EOF
# Generated by setup.sh on $(date -u +"%Y-%m-%d %H:%M UTC")
# Do NOT commit this file to git.

HTTP_PORT=${HTTP_PORT}

POSTGRES_DB=craftcontrol
POSTGRES_USER=craftcontrol
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

REDIS_PASSWORD=${REDIS_PASSWORD}

JWT_SECRET=${JWT_SECRET}
JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
JWT_EXPIRES_IN=15m
JWT_REFRESH_EXPIRES_IN=7d

BRIDGE_SECRET=${BRIDGE_SECRET}
GAME_VM_HOST=${GAME_VM_HOST}

IMAGE_TAG=latest
EOF

chmod 600 "$ENV_FILE"

# ── Summary ──────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}${BOLD}✓ .env created successfully!${RESET}"
echo ""
echo -e "${BOLD}════ ACTION REQUIRED ════════════════════════════${RESET}"
echo -e "${YELLOW}Copy the BRIDGE_SECRET to your Minecraft server:${RESET}"
echo ""
echo -e "  DiscoPanel → Environment Variables → add:"
echo -e "  ${BOLD}BRIDGE_SECRET=${BRIDGE_SECRET}${RESET}"
echo ""
echo -e "${BOLD}════ Next step ══════════════════════════════════${RESET}"
echo -e "  Run: ${BOLD}make deploy${RESET}"
echo ""
